spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tCQqwSadkhfY8zrjXb5
      secret-key: ruTeMCXOC43LAG842QzxRhWakOKlcX
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gmall-lcb
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        template_id: TPL_0000
        appcode: 1689c0dff9d34163aca516b53b8b7171

  application:
    name: gmall-third-party

server:
  port: 30000
