spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.248.135:3306/gmall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: true
  redis:
    host: 192.168.248.135
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.lcb.gmall: error



